version: '3'

services:
  pricing:
    build: ./
    depends_on:
      - 'database'
    ports:
      - '3001:3001'

  database:
    image: mysql:latest
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"